<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <table>
      <tr>
        <td></td>
        <td>Dl</td>
        <td>DM</td>
        <td>DX</td>
        <td>DJ</td>
        <td>DV</td>
      </tr>
      <tr>
        <td>16-17</td>
        <td>M6</td>
        <td>M7</td>
        <td>TUT</td>
        <td>M7</td>
        <td>M8</td>
      </tr>
      <tr>
        <td>17-18</td>
        <td>M6</td>
        <td>M7</td>
        <td>M9</td>
        <td>M7</td>
        <td>M8</td>

      </tr>
      <tr>
        <td>18-18:30</td>
        <td>PATI</td>
        <td>PATI</td>
        <td>PATI</td>
        <td>PATI</td>
        <td>PATI</td>
      </tr>
      <tr>
        <td>18:30-19:30</td>
        <td>M6</td>
        <td>M8</td>
        <td>M9</td>
        <td>M8</td>
        <td>M8</td>
      </tr>
      <tr>
        <td>19:30-20:30</td>
        <td>M6</td>
        <td>M8</td>
        <td>M9</td>
        <td>M8</td>
        <td>M9</td>
      </tr>




    </table>

  </body>
</html>
